### ISSUE TITLE
EXAMPLE - /assign & /unassign

### ISSUE THREAD

**Issue by jpmcb** [jpmcb/prow-github-actions#14]
Using the assign command, one can assign themselves or other users. The target user must be an org member, a repo collaborator, or have previously commented on the issue / PR.

**Comment by jpmcb** [comment]
/unassign

The `unassign` command works much the same as the `assign` command. The target must have already been assigned.

**Comment by hzxuzhonghu** [comment]
hi, i could not assign others in my repo.

Test

/assign @jpmcb
