### ISSUE TITLE
Support OWNERS files

### ISSUE THREAD

**Issue by carolynvs** [jpmcb/prow-github-actions#44]
**Is your feature request related to a problem? Please describe.**
I want to specify exactly who can provide reviews and approve pull requests since there are a lot of people in the organization who do not qualify as reviewers and approvers.

**Describe the solution you'd like**
I'd be happy with any way to specify a named set of people or teams that can be reviewers and approvers. Either by reading the [OWNERS](https://www.kubernetes.dev/docs/guide/owners/) file (like prow does), or something more simple like just passing the action a list of names in the workflow file. I realize the full logic of owners files is pretty complex, and I just care about having a bit more control than just org membership.

**Describe alternatives you've considered**
N/A

**Additional context**
I'm happy to submit a PR for this if this is a welcome feature.

**Comment by jpmcb** [comment]
Thanks for opening this feature request! I think this is a great idea.

> Either by reading the [OWNERS](https://www.kubernetes.dev/docs/guide/owners/) file (like prow does)

I think that's the way to go on this but we could also do something simple in the action yaml file too.

I'm happy to accept a PR on this! 🚀

**Comment by carolynvs** [comment]
Excellent, I'll work on it this weekend.
