### ISSUE TITLE
Suggestion: Reply with comment with the slash command result

### ISSUE THREAD

**Issue by carolynvs** [jpmcb/prow-github-actions#53]
As I was implementing [OWNERS file support](#51 ), I noticed that from the commenter's perspective it's not always clear when the command failed, and where to see what happened. Other github bots will usually reply back when it can't execute the command or tells you what it did on your behalf.

What if we had the bot post back if the commenter isn't authorized to run that command, or the result of what the action did (e.g. added a label)? I'm not sure if chattiness is a problem but it seems like this would help users quickly know how their command worked out.

carolynvs: /lgtm
prow: Cannot apply the lgtm label because @carolynvs is not in the reviewers role in the OWNERS file

carolynvs: /lgtm
prow: Added lgtm label

subsequent /lgtm commands won't print anything because the label is already applied

carolynvs: /lgtm cancel
prow: Removed lgtm label

carolynvs: /approve
prow: The pull request was approved by @carolynvs

**Comment by carolynvs** [comment]
It could be annoying to get an extra notification for each slash command though. We could just reply with errors and otherwise people can assume it worked if they don't hear back?

**Comment by jpmcb** [comment]
> It could be annoying to get an extra notification for each slash command though. We could just reply with errors and otherwise people can assume it worked if they don't hear back?

Hmmm great thought. Yeah, I'm thinking the default user experience should be "it just works TM" and they won't see an error notification nor message unless there is a failure.

**Comment by carolynvs** [comment]
Oops, I forgot to close this in my last PR https://github.com/jpmcb/prow-github-actions/pull/59. I implemented this so that prow only leaves a comment when it was unable to run the slash command.
